[build]
shell = "bash"

[features]
seeds = false
init-if-needed = true

[programs.devnet]
necro_migrate = "2z3U1Wwq7bgHnkEuD5Yfw97g8uGyimDyRafRar21Bsva"

[programs.localnet]
necro_migrate = "2z3U1Wwq7bgHnkEuD5Yfw97g8uGyimDyRafRar21Bsva"

[programs.mainnet]
necro_migrate = "2z3U1Wwq7bgHnkEuD5Yfw97g8uGyimDyRafRar21Bsva"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "bash ./tests/run.sh"
