[package]
name = "necro_migrate"
version = "0.1.0"
edition = "2021"

[dependencies]
anchor-lang = "0.30"
anchor-spl = "0.30"
solana-program = "1.18"
spl-token = "4"
sha2 = "0.10"
byteorder = "1.4"

[lib]
crate-type = ["cdylib", "rlib"]
